#!/bin/bash

# Raúl RC
# Created September 23, 2019
# raul.rodriguezcruces@mcgill.ca
#
############################################################################
# Sets python 2.7 as default on a given sesion
# NOTE:
# MUST be sourced from .profile:
# alias py2='source /host/yeatman/local_raid/rcruces/git_here/miscellaneous/conda2'
############################################################################

# Adds the conda2 path to the env PATH variable
export PATH=/host/yeatman/local_raid/rcruces/anaconda2/bin/:${PATH}

# Creates the necesary env variables to call python2.7
#export PYTHONPATH="/host/yeatman/local_raid/rcruces/anaconda2/bin/python2.7:/host/yeatman/local_raid/rcruces/anaconda2/bin"
#export PYTHONHOME="/host/yeatman/local_raid/rcruces/anaconda2"
#export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/host/yeatman/local_raid/rcruces/anaconda2/lib"

# Language utilities
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# print a QC
echo -e "\n\033[38;5;69m-------------------------------------------------------------
        Setting \033[38;5;7m \033[48;5;4m python 2.7 \033[0m \033[38;5;69m version
\033[38;5;141m PYTHONPATH\033[38;5;69m      = ${PYTHONPATH}\033[0m
\033[38;5;141m PYTHONHOME\033[38;5;69m      = ${PYTHONHOME}\033[0m
\033[38;5;141m LC_ALL\033[38;5;69m		 = ${LC_ALL}\033[0m
\033[38;5;141m LANG\033[38;5;69m		 = ${LANG}\033[0m
\033[38;5;141m LD_LIBRARY_PATH\033[38;5;69m = ${LD_LIBRARY_PATH}\033[0m
\033[38;5;69m-------------------------------------------------------------\033[0m\n
"
