#!/bin/bash

# Raúl RC
# Created September 23, 2019
# raul.rodriguezcruces@mcgill.ca
#
############################################################################
# Unsets ANY python version
# NOTE:
# MUST be sourced from .profile:
# alias pyu='source /host/yeatman/local_raid/rcruces/git_here/miscellaneous/conda-unset'
############################################################################

# REMOVES the conda from the PATH  and LD_LIBRARY_PATH variable
PATH=$(IFS=':';p=($PATH);unset IFS;p=(${p[@]%%*anaconda*});IFS=':';echo "${p[*]}";unset IFS)
export PATH

# Creates the necesary env variables to call python2.7
unset PYTHONPATH
unset PYTHONHOME
LD_LIBRARY_PATH=$(IFS=':';p=($LD_LIBRARY_PATH);unset IFS;p=(${p[@]%%*anaconda*});IFS=':';echo "${p[*]}";unset IFS)
export LD_LIBRARY_PATH

# Language utilities
unset LC_ALL
unset LANG

# print a QC
echo -e "\n\033[38;5;69m-------------------------------------------------------------
        UNSET \033[38;5;7m \033[48;5;4m python \033[0m \033[38;5;69m version
\033[38;5;141m PYTHONPATH\033[38;5;69m      = ${PYTHONPATH}\033[0m
\033[38;5;141m PYTHONHOME\033[38;5;69m      = ${PYTHONHOME}\033[0m
\033[38;5;141m LC_ALL\033[38;5;69m		 = ${LC_ALL}\033[0m
\033[38;5;141m LANG\033[38;5;69m		 = ${LANG}\033[0m
\033[38;5;141m LD_LIBRARY_PATH\033[38;5;69m = ${LD_LIBRARY_PATH}\033[0m
\033[38;5;69m-------------------------------------------------------------\033[0m\n
"
